
const recipesData = [
    {
      name: "Butter Chicken",
      chef: "Chef Raj",
      totalRatings: 1200,
      avgRating: 4.9,
      uploadedOn: "2024-02-10",
      mealType: "Dinner",
      dishType: "Curry",
      testKitchenApproved: true,
      contestWinner: true,
      featured: true,
      description: "A rich and creamy tomato-based curry with tender chicken pieces.",
      imgUrl: "https://i.pinimg.com/564x/48/14/a4/4814a46296c8c09a27f6e6b144e5c8a3.jpg"
    },
    {
      name: "Paneer Tikka",
      chef: "Chef Ananya",
      totalRatings: 950,
      avgRating: 4.7,
      uploadedOn: "2024-02-05",
      mealType: "Appetizer",
      dishType: "Grilled",
      testKitchenApproved: true,
      contestWinner: false,
      featured: false,
      description: "Marinated paneer cubes grilled to perfection with smoky flavors.",
      imgUrl: "https://i.pinimg.com/564x/1c/92/9f/1c929fd8dc051b3a8d5bb0c41eaf2363.jpg"
    },
    {
      name: "Hyderabadi Biryani",
      chef: "Chef Ameer",
      totalRatings: 1800,
      avgRating: 4.9,
      uploadedOn: "2024-01-20",
      mealType: "Lunch",
      dishType: "Rice",
      testKitchenApproved: true,
      contestWinner: true,
      featured: true,
      description: "A fragrant and flavorful biryani layered with marinated meat and basmati rice.",
      imgUrl: "https://i.pinimg.com/564x/25/6e/a8/256ea8bb90d4a499f8b1787c905b7425.jpg"
    },
    {
      name: "Masala Dosa",
      chef: "Chef Suresh",
      totalRatings: 1300,
      avgRating: 4.8,
      uploadedOn: "2024-02-01",
      mealType: "Breakfast",
      dishType: "South Indian",
      testKitchenApproved: true,
      contestWinner: false,
      featured: false,
      description: "A crispy dosa stuffed with spicy mashed potatoes, served with chutney and sambar.",
      imgUrl: "https://i.pinimg.com/564x/09/65/41/09654121e4c32fdedf5ff43bcd756ac3.jpg"
    },
    {
      name: "Chole Bhature",
      chef: "Chef Manjeet",
      totalRatings: 1150,
      avgRating: 4.7,
      uploadedOn: "2024-01-30",
      mealType: "Breakfast",
      dishType: "North Indian",
      testKitchenApproved: true,
      contestWinner: false,
      featured: true,
      description: "A spicy chickpea curry served with deep-fried fluffy bread.",
      imgUrl: "https://i.pinimg.com/564x/f4/1b/46/f41b46dc9d7a82a44bc0ff6e477e2eb1.jpg"
    },
    {
      name: "Pani Puri",
      chef: "Chef Kavita",
      totalRatings: 2200,
      avgRating: 4.9,
      uploadedOn: "2024-02-15",
      mealType: "Snack",
      dishType: "Street Food",
      testKitchenApproved: true,
      contestWinner: true,
      featured: true,
      description: "Crispy puris filled with tangy and spicy flavored water.",
      imgUrl: "https://i.pinimg.com/564x/31/5c/7c/315c7cd3a7f929960bb10d2675b93607.jpg"
    },
    {
      name: "Rajma Chawal",
      chef: "Chef Sunil",
      totalRatings: 900,
      avgRating: 4.6,
      uploadedOn: "2024-01-25",
      mealType: "Lunch",
      dishType: "Rice",
      testKitchenApproved: true,
      contestWinner: false,
      featured: false,
      description: "Red kidney beans cooked in a spicy tomato gravy, served with steamed rice.",
      imgUrl: "https://i.pinimg.com/564x/60/3b/4f/603b4f4e1a63ea84a48ac29a6617a1aa.jpg"
    },
    {
      name: "Dal Makhani",
      chef: "Chef Vikram",
      totalRatings: 1100,
      avgRating: 4.8,
      uploadedOn: "2024-02-12",
      mealType: "Dinner",
      dishType: "Curry",
      testKitchenApproved: true,
      contestWinner: false,
      featured: true,
      description: "A rich and creamy lentil curry made with black gram and butter.",
      imgUrl: "https://i.pinimg.com/564x/2a/eb/12/2aeb12eeb44ac1ccdfb845d875bb18a5.jpg"
    },
    {
      name: "Aloo Paratha",
      chef: "Chef Neha",
      totalRatings: 1000,
      avgRating: 4.7,
      uploadedOn: "2024-01-28",
      mealType: "Breakfast",
      dishType: "Flatbread",
      testKitchenApproved: true,
      contestWinner: false,
      featured: false,
      description: "A stuffed wheat flatbread filled with spiced mashed potatoes.",
      imgUrl: "https://i.pinimg.com/564x/69/99/5e/69995e3d6547766a6a07b93b8a67ec6c.jpg"
    },
    {
      name: "Gulab Jamun",
      chef: "Chef Rakesh",
      totalRatings: 1300,
      avgRating: 4.9,
      uploadedOn: "2024-02-08",
      mealType: "Dessert",
      dishType: "Sweet",
      testKitchenApproved: true,
      contestWinner: true,
      featured: true,
      description: "Soft and spongy milk-based dumplings soaked in sugar syrup.",
      imgUrl: "https://i.pinimg.com/564x/7a/6e/53/7a6e537e0e7963044d0fd09f06a3a1cd.jpg"
    },
    {
      name: "Samosa",
      chef: "Chef Pooja",
      totalRatings: 1900,
      avgRating: 4.8,
      uploadedOn: "2024-01-27",
      mealType: "Snack",
      dishType: "Street Food",
      testKitchenApproved: true,
      contestWinner: false,
      featured: false,
      description: "A crispy, deep-fried pastry filled with spicy mashed potatoes and peas.",
      imgUrl: "https://i.pinimg.com/564x/c5/82/40/c5824047221b3e438be3d3663208427b.jpg"
    },
    {
      name: "Dhokla",
      chef: "Chef Pratik",
      totalRatings: 800,
      avgRating: 4.6,
      uploadedOn: "2024-02-03",
      mealType: "Snack",
      dishType: "Gujarati",
      testKitchenApproved: true,
      contestWinner: false,
      featured: false,
      description: "A spongy, steamed savory cake made with fermented chickpea flour.",
      imgUrl: "https://i.pinimg.com/564x/0b/eb/44/0beb445e31e5e4e61a66b7c380cfc9b4.jpg"
    }
  ];
  
  export default recipesData;
  